app:
  name: "API Box v2"
  dir: "/files"
  port: 9000
  # user's list who have permissions to add/update/delete docs
  curd:
    - username
    - user_a

auth_secrets:
  username: password
  user_a: password_a
  user_b: password_b
