app:
  name: "API Box"
  dir: "./files"
  port: 9000
  session_expire: 30 #minutes
  # user's list who have permissions to add/update/delete docs
  crud:
    - root
    - user_a

auth_secrets:
  root: 12345
  user_a: password_a
  user_b: password_b
